name: Pull Request Validation

on:
  pull_request:
    branches:
      - develop

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install -g htmlhint stylelint stylelint-config-standard

      - name: Lint HTML
        run: htmlhint "src/**/*.html"

      - name: Lint CSS
        run: stylelint "styles/**/*.css"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Parcel
        run: npm install -g parcel-bundler

      - name: Build website
        run: parcel build src/index.html
