name: Pull Request Validation

on:
  pull_request:
    branches:
      - develop

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint HTML and CSS Rsc
        run: |
          npx htmlhint "**/*.html"
          npx stylelint "**/*.css"

  build:
    needs: linting
    runs-on: ubuntu-latest
    steps:
      - name: name: Try Build
        run: |
          npx parcel build "./src/index.html" --dist-dir "./dev" --public-url "./"